### ISSUE TITLE
Improve gobstones error when the code includes 'ñ'

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-xgobstones-runner#90] opened 2017-02-13 19:41 UTC

**Comment by flbulgarelli** [comment] 2017-02-15 03:44
Duplicate of #85

**Closed by flbulgarelli** 2017-02-15 03:44 UTC

**Comment by flbulgarelli** [comment] 2017-02-19 13:17
![image](https://cloud.githubusercontent.com/assets/677436/23102680/92250a96-f68c-11e6-9a14-cb17e316c36a.png)
